# Generated by Django 4.1.4 on 2023-01-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conference_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
