# Generated by Django 4.1.4 on 2023-01-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0002_alter_conference_conference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='ugc_listed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
