# Generated by Django 4.1.4 on 2023-01-14 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0004_alter_conference_conference_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('role', models.CharField(choices=[('HOD', 'HOD'), ('Other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('department_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('password_confirm', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='Faculty_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CSE.faculty'),
        ),
    ]
