# Generated by Django 4.1.4 on 2023-01-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0005_faculty_conference_faculty_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='Faculty_name',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
