# Generated by Django 4.1.4 on 2023-01-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
