# Generated by Django 4.1.4 on 2023-01-15 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSE', '0013_alter_conference_fac_name_alter_journal_fac_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='fac_name',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='fac_name',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
