# Generated by Django 4.1.4 on 2023-01-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0015_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='fac_name',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
